#!/bin/bash

# System Test Script
# Run tests on already running autonomy system

set -e

# Colors
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m'

# Config
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_ROOT="$(dirname "$SCRIPT_DIR")"
TEST_TYPE=${1:-integration}

print_info() { echo -e "${BLUE}[INFO]${NC} $1"; }
print_success() { echo -e "${GREEN}[✓]${NC} $1"; }
print_warning() { echo -e "${YELLOW}[⚠]${NC} $1"; }
print_error() { echo -e "${RED}[✗]${NC} $1"; }

check_system_running() {
    if ! ros2 node list &>/dev/null; then
        print_error "No ROS2 system detected. Launch system first:"
        echo "  ./scripts/system_launch.sh"
        exit 1
    fi

    local nodes=$(ros2 node list | wc -l)
    print_success "System running with $nodes nodes"
}

run_unit_tests() {
    print_info "Running unit tests..."

    cd "$PROJECT_ROOT"
    if python -m pytest tests/unit/ -v --tb=short --maxfail=5; then
        print_success "Unit tests passed"
        return 0
    else
        print_error "Unit tests failed"
        return 1
    fi
}

run_integration_tests() {
    print_info "Running integration tests..."

    cd "$PROJECT_ROOT"
    if python -m pytest tests/integration/ -v --tb=short --maxfail=3; then
        print_success "Integration tests passed"
        return 0
    else
        print_error "Integration tests failed"
        return 1
    fi
}

run_system_tests() {
    print_info "Running system tests..."

    cd "$PROJECT_ROOT"
    if python -m pytest tests/system/ -v --tb=short --maxfail=3; then
        print_success "System tests passed"
        return 0
    else
        print_warning "Some system tests failed (may be expected)"
        return 0
    fi
}

test_basic_functionality() {
    print_info "Testing basic system functionality..."

    local issues=0

    # Test state machine
    if ros2 topic echo /state_machine/current_state --once --timeout 3 &>/dev/null; then
        print_success "State machine responding"
    else
        print_error "State machine not responding"
        ((issues++))
    fi

    # Test safety system
    if ros2 topic echo /safety/dashboard_status --once --timeout 3 &>/dev/null; then
        print_success "Safety system responding"
    else
        print_warning "Safety system not responding"
    fi

    # Test navigation (if running)
    if ros2 node list 2>/dev/null | grep -q navigation; then
        if ros2 topic info /navigation/cmd_vel &>/dev/null; then
            print_success "Navigation system ready"
        else
            print_warning "Navigation topics not available"
        fi
    fi

    # Test vision (if running)
    if ros2 node list 2>/dev/null | grep -q computer_vision; then
        if ros2 topic info /camera/image_raw &>/dev/null; then
            print_success "Vision system has camera feed"
        else
            print_warning "Vision system camera feed not available"
        fi
    fi

    return $issues
}

test_safety_integration() {
    print_info "Testing safety system integration..."

    # Test emergency stop service
    if ros2 service list 2>/dev/null | grep -q "software_estop"; then
        print_success "Emergency stop service available"
    else
        print_error "Emergency stop service missing"
        return 1
    fi

    # Test safety state changes don't break other systems
    print_info "Testing safety state transitions..."
    # This would require more complex testing logic

    return 0
}

generate_test_report() {
    local report_file="system_test_report_$(date +%Y%m%d_%H%M%S).txt"

    cat > "$report_file" << EOF
URC 2026 System Test Report
===========================

Test Type: $TEST_TYPE
Timestamp: $(date)

System Status:
$(ros2 node list 2>/dev/null | wc -l) nodes running
$(ros2 topic list 2>/dev/null | wc -l) topics active

Test Results Summary:
- Basic Functionality: $(test_basic_functionality &>/dev/null && echo "PASS" || echo "ISSUES")
- Safety Integration: $(test_safety_integration &>/dev/null && echo "PASS" || echo "FAIL")

Next Steps:
1. Review test output above for specific issues
2. Run individual subsystem tests if needed:
   ./scripts/test_navigation.sh
   ./scripts/start_safety_testing.sh
3. Check system health: ./scripts/health_check.sh
4. Generate performance report: ./scripts/benchmark_system.sh

Report generated by system_test.sh
EOF

    print_success "Test report saved: $report_file"
}

usage() {
    echo "Usage: $0 [test_type]"
    echo ""
    echo "Run tests on running autonomy system"
    echo ""
    echo "Test Types:"
    echo "  unit         Run unit tests only"
    echo "  integration  Run integration tests only (default)"
    echo "  system       Run system-level tests only"
    echo "  all          Run all test types"
    echo "  functional   Test basic functionality only"
    echo ""
    echo "Prerequisites:"
    echo "  System must be running: ./scripts/system_launch.sh"
    echo ""
    echo "Examples:"
    echo "  $0 integration    # Run integration tests"
    echo "  $0 functional     # Quick functionality check"
    echo "  $0 all           # Run all tests"
}

main() {
    case $1 in
        "unit")
            echo "🧪 Unit Tests"
            echo "============="
            ;;
        "integration")
            echo "🔗 Integration Tests"
            echo "===================="
            ;;
        "system")
            echo "🏗️ System Tests"
            echo "==============="
            ;;
        "functional")
            echo "⚙️ Functional Tests"
            echo "==================="
            ;;
        "all")
            echo "🚀 All Tests"
            echo "============"
            ;;
        "help"|"-h"|"--help")
            usage
            exit 0
            ;;
        *)
            echo "🔗 Integration Tests (default)"
            echo "=============================="
            TEST_TYPE="integration"
            ;;
    esac

    check_system_running

    local test_failures=0

    case $TEST_TYPE in
        "unit")
            run_unit_tests || ((test_failures++))
            ;;
        "integration")
            run_integration_tests || ((test_failures++))
            ;;
        "system")
            run_system_tests || ((test_failures++))
            ;;
        "functional")
            test_basic_functionality || ((test_failures++))
            test_safety_integration || ((test_failures++))
            ;;
        "all")
            run_unit_tests || ((test_failures++))
            run_integration_tests || ((test_failures++))
            run_system_tests || ((test_failures++))
            test_basic_functionality || ((test_failures++))
            ;;
    esac

    generate_test_report

    if [ $test_failures -eq 0 ]; then
        print_success "🎉 All tests in category '$TEST_TYPE' completed successfully!"
    else
        print_warning "⚠️ $test_failures test categories had issues"
    fi

    echo ""
    echo "For detailed analysis:"
    echo "  ./scripts/health_check.sh     # System health"
    echo "  ./scripts/benchmark_system.sh # Performance metrics"
}

main "$@"
