URC Machiato 2026 Autonomy: autonomy_autonomous_typing.keyboard_dictionary.KeyboardDictionary Class Reference
autonomy_autonomous_typing.keyboard_dictionary.KeyboardDictionary Class Reference
Public Member Functions
def __init__ (self)
Optional[Tuple[float, float]] get_key_position (self, str key)
Optional[np.ndarray] get_key_3d_position (self, str key, float z_offset=0.0)
Optional[Dict[str, np.ndarray]] get_key_press_trajectory (self, str key)
list get_all_keys (self)
bool is_valid_key (self, str key)
Dict get_press_params (self)
None set_press_params (self, **kwargs)
Public Attributes
keyboard_layout
press_params
Detailed Description
Manages keyboard layout with 3D positions relative to keyboard frame.
The keyboard frame origin is assumed to be at one corner of the keyboard,
typically where markers are placed. All key positions are relative to this origin.
Definition at line 24 of file keyboard_dictionary.py.
Constructor & Destructor Documentation
__init__()
def autonomy_autonomous_typing.keyboard_dictionary.KeyboardDictionary.__init__ (self)
Initialize keyboard layout dictionary.
Definition at line 32 of file keyboard_dictionary.py.
Member Function Documentation
get_all_keys()
list autonomy_autonomous_typing.keyboard_dictionary.KeyboardDictionary.get_all_keys (self)
Get list of all supported keys.
Definition at line 179 of file keyboard_dictionary.py.
References autonomy_autonomous_typing.keyboard_dictionary.KeyboardDictionary.keyboard_layout.
get_key_3d_position()
Optional[np.ndarray] autonomy_autonomous_typing.keyboard_dictionary.KeyboardDictionary.get_key_3d_position (self, str key, float z_offset = 0.0)
Get 3D position of a key relative to keyboard frame origin.
Args:
    key: Key name
    z_offset: Z position in keyboard frame (0 = at surface, positive = above)
Returns:
    3D numpy array [x, y, z] or None if key not found
Definition at line 132 of file keyboard_dictionary.py.
References autonomy_autonomous_typing.keyboard_dictionary.KeyboardDictionary.get_key_position().
get_key_position()
Optional[Tuple[float, float]] autonomy_autonomous_typing.keyboard_dictionary.KeyboardDictionary.get_key_position (self, str key)
Get (x, y) position of a key relative to keyboard frame origin.
Args:
    key: Key name (e.g., 'q', 'space', 'backspace')
Returns:
    Tuple of (x, y) in meters, or None if key not found
Definition at line 116 of file keyboard_dictionary.py.
References autonomy_autonomous_typing.keyboard_dictionary.KeyboardDictionary.keyboard_layout.
Referenced by autonomy_autonomous_typing.keyboard_dictionary.KeyboardDictionary.get_key_3d_position(), and autonomy_autonomous_typing.keyboard_dictionary.KeyboardDictionary.get_key_press_trajectory().
get_key_press_trajectory()
Optional[Dict[str, np.ndarray]] autonomy_autonomous_typing.keyboard_dictionary.KeyboardDictionary.get_key_press_trajectory (self, str key)
Get 3D trajectory for pressing a key (approach -> press -> retract).
Args:
    key: Key name
Returns:
    Dict with 'approach', 'press', and 'retract' positions, or None
Definition at line 153 of file keyboard_dictionary.py.
References autonomy_autonomous_typing.keyboard_dictionary.KeyboardDictionary.get_key_position(), and autonomy_autonomous_typing.keyboard_dictionary.KeyboardDictionary.press_params.
get_press_params()
Dict autonomy_autonomous_typing.keyboard_dictionary.KeyboardDictionary.get_press_params (self)
Get keyboard pressing parameters.
Definition at line 187 of file keyboard_dictionary.py.
References autonomy_autonomous_typing.keyboard_dictionary.KeyboardDictionary.press_params.
is_valid_key()
bool autonomy_autonomous_typing.keyboard_dictionary.KeyboardDictionary.is_valid_key (self, str key)
Check if a key is in the keyboard layout.
Definition at line 183 of file keyboard_dictionary.py.
References autonomy_autonomous_typing.keyboard_dictionary.KeyboardDictionary.keyboard_layout.
set_press_params()
None autonomy_autonomous_typing.keyboard_dictionary.KeyboardDictionary.set_press_params (self, ** kwargs)
Update pressing parameters.
Definition at line 191 of file keyboard_dictionary.py.
References autonomy_autonomous_typing.keyboard_dictionary.KeyboardDictionary.press_params.
Member Data Documentation
keyboard_layout
autonomy_autonomous_typing.keyboard_dictionary.KeyboardDictionary.keyboard_layout
Definition at line 34 of file keyboard_dictionary.py.
Referenced by autonomy_autonomous_typing.keyboard_dictionary.KeyboardDictionary.get_all_keys(), autonomy_autonomous_typing.keyboard_dictionary.KeyboardDictionary.get_key_position(), and autonomy_autonomous_typing.keyboard_dictionary.KeyboardDictionary.is_valid_key().
press_params
autonomy_autonomous_typing.keyboard_dictionary.KeyboardDictionary.press_params
Definition at line 37 of file keyboard_dictionary.py.
Referenced by autonomy_autonomous_typing.keyboard_dictionary.KeyboardDictionary.get_key_press_trajectory(), autonomy_autonomous_typing.keyboard_dictionary.KeyboardDictionary.get_press_params(), and autonomy_autonomous_typing.keyboard_dictionary.KeyboardDictionary.set_press_params().
The documentation for this class was generated from the following file:
code/autonomous_typing/autonomy_autonomous_typing/keyboard_dictionary.py