URC Machiato 2026 Autonomy: ros2_node_template.YourNodeName Class Reference
ros2_node_template.YourNodeName Class Reference
Public Member Functions
def __init__ (self)
def example_callback (self, msg)
def example_service_callback (self, request, response)
def control_loop (self)
def health_check_callback (self)
def validate_input (self, data)
def publish_status (self)
def cleanup (self)
Public Attributes
update_rate
param1
param2
enable_feature
qos_sensor
qos_control
qos_state
example_pub
example_sub
example_service
control_timer
is_active
last_update_time
error_count
Detailed Description
ROS 2 node for [brief description].
[Detailed description of what this node does, its responsibilities,
and how it fits into the overall autonomy system.]
Publishers:
    [topic_name] ([msg_type]): [description]
Subscribers:
    [topic_name] ([msg_type]): [description]
Services:
    [service_name] ([srv_type]): [description]
Parameters:
    [param_name] ([type]): [description] (default: [value])
Definition at line 28 of file ros2_node_template.py.
Constructor & Destructor Documentation
__init__()
def ros2_node_template.YourNodeName.__init__ (self)
Initialize the node.
Definition at line 48 of file ros2_node_template.py.
Member Function Documentation
cleanup()
def ros2_node_template.YourNodeName.cleanup (self)
Clean up resources before shutdown.
Definition at line 255 of file ros2_node_template.py.
control_loop()
def ros2_node_template.YourNodeName.control_loop (self)
Main control loop executed at update rate.
Definition at line 208 of file ros2_node_template.py.
References ros2_node_template.YourNodeName.error_count, ros2_node_template.YourNodeName.is_active, and ros2_node_template.YourNodeName.last_update_time.
example_callback()
def ros2_node_template.YourNodeName.example_callback (self, msg)
Handle example subscriber messages.
Definition at line 167 of file ros2_node_template.py.
References ros2_node_template.YourNodeName.error_count, and ros2_node_template.YourNodeName.last_update_time.
example_service_callback()
def ros2_node_template.YourNodeName.example_service_callback (self, request, response)
Handle example service calls.
Definition at line 183 of file ros2_node_template.py.
health_check_callback()
def ros2_node_template.YourNodeName.health_check_callback (self)
Periodic health check.
Definition at line 230 of file ros2_node_template.py.
References ros2_node_template.YourNodeName.error_count, and ros2_node_template.YourNodeName.last_update_time.
Referenced by digital_twin_manager.DigitalTwinManager.__init__().
publish_status()
def ros2_node_template.YourNodeName.publish_status (self)
Publish current node status.
Definition at line 250 of file ros2_node_template.py.
Referenced by autonomy_calibration.calibration_manager.CalibrationManager.calibrate_camera_callback(), autonomy_calibration.calibration_manager.CalibrationManager.load_parameters_callback(), and autonomy_calibration.calibration_manager.CalibrationManager.validate_calibration_callback().
validate_input()
def ros2_node_template.YourNodeName.validate_input (self, data)
Validate input data.
Definition at line 242 of file ros2_node_template.py.
Member Data Documentation
control_timer
ros2_node_template.YourNodeName.control_timer
Definition at line 146 of file ros2_node_template.py.
enable_feature
ros2_node_template.YourNodeName.enable_feature
Definition at line 67 of file ros2_node_template.py.
error_count
ros2_node_template.YourNodeName.error_count
Definition at line 159 of file ros2_node_template.py.
Referenced by ros2_node_template.YourNodeName.control_loop(), ros2_node_template.YourNodeName.example_callback(), and ros2_node_template.YourNodeName.health_check_callback().
example_pub
ros2_node_template.YourNodeName.example_pub
Definition at line 112 of file ros2_node_template.py.
example_service
ros2_node_template.YourNodeName.example_service
Definition at line 138 of file ros2_node_template.py.
example_sub
ros2_node_template.YourNodeName.example_sub
Definition at line 124 of file ros2_node_template.py.
is_active
ros2_node_template.YourNodeName.is_active
Definition at line 157 of file ros2_node_template.py.
Referenced by ros2_node_template.YourNodeName.control_loop().
last_update_time
ros2_node_template.YourNodeName.last_update_time
Definition at line 158 of file ros2_node_template.py.
Referenced by ros2_node_template.YourNodeName.control_loop(), ros2_node_template.YourNodeName.example_callback(), and ros2_node_template.YourNodeName.health_check_callback().
param1
ros2_node_template.YourNodeName.param1
Definition at line 65 of file ros2_node_template.py.
param2
ros2_node_template.YourNodeName.param2
Definition at line 66 of file ros2_node_template.py.
qos_control
ros2_node_template.YourNodeName.qos_control
Definition at line 97 of file ros2_node_template.py.
qos_sensor
ros2_node_template.YourNodeName.qos_sensor
Definition at line 91 of file ros2_node_template.py.
qos_state
ros2_node_template.YourNodeName.qos_state
Definition at line 103 of file ros2_node_template.py.
update_rate
ros2_node_template.YourNodeName.update_rate
Definition at line 64 of file ros2_node_template.py.
The documentation for this class was generated from the following file:
code/templates/ros2_node_template.py