URC Machiato 2026 Autonomy: autonomy_state_machine.led_state_publisher.LEDStatePublisher Class Reference
autonomy_state_machine.led_state_publisher.LEDStatePublisher Class Reference
Public Member Functions
def __init__ (self, Node node)
None update_state (self, SystemState state, Optional[AutonomousSubstate] substate=None)
None signal_waypoint_success (self)
None signal_transition_start (self)
None signal_error (self, str error_type="GENERAL")
None signal_success (self, str success_type="GENERAL")
Public Attributes
node
led_info_publisher
Detailed Description
Publishes LED state information for URC competition requirements.
Per URC 2026 rules:
- Red: Autonomous operation
- Blue: Teleoperation (manually driving)
- Flashing Green: Successful arrival at target
This class publishes state information; the LED controller decides
actual colors and patterns.
Definition at line 18 of file led_state_publisher.py.
Constructor & Destructor Documentation
__init__()
def autonomy_state_machine.led_state_publisher.LEDStatePublisher.__init__ (self, Node node)
Initialize LED state publisher.
Args:
    node: Parent ROS2 node
Definition at line 31 of file led_state_publisher.py.
Member Function Documentation
signal_error()
None autonomy_state_machine.led_state_publisher.LEDStatePublisher.signal_error (self, str error_type = "GENERAL")
Signal an error condition.
Args:
    error_type: Type of error
Definition at line 148 of file led_state_publisher.py.
References autonomy_state_machine.led_state_publisher.LEDStatePublisher._publish_led_info().
signal_success()
None autonomy_state_machine.led_state_publisher.LEDStatePublisher.signal_success (self, str success_type = "GENERAL")
Signal a success condition.
Args:
    success_type: Type of success
Definition at line 160 of file led_state_publisher.py.
References autonomy_state_machine.led_state_publisher.LEDStatePublisher._publish_led_info().
signal_transition_start()
None autonomy_state_machine.led_state_publisher.LEDStatePublisher.signal_transition_start (self)
Signal that a state transition is starting.
Definition at line 141 of file led_state_publisher.py.
References autonomy_state_machine.led_state_publisher.LEDStatePublisher._publish_led_info().
signal_waypoint_success()
None autonomy_state_machine.led_state_publisher.LEDStatePublisher.signal_waypoint_success (self)
Signal successful arrival at waypoint (flashing green per URC rules).
Definition at line 69 of file led_state_publisher.py.
References autonomy_state_machine.led_state_publisher.LEDStatePublisher._publish_led_info(), and autonomy_state_machine.led_state_publisher.LEDStatePublisher.led_info_publisher.
update_state()
None autonomy_state_machine.led_state_publisher.LEDStatePublisher.update_state (self, SystemState state, Optional[AutonomousSubstate] substate = None)
Update LED information based on state.
Args:
    state: Current system state
    substate: Current autonomous substate (if applicable)
Definition at line 47 of file led_state_publisher.py.
References autonomy_state_machine.led_state_publisher.LEDStatePublisher._determine_led_info(), and autonomy_state_machine.led_state_publisher.LEDStatePublisher._publish_led_info().
Member Data Documentation
led_info_publisher
autonomy_state_machine.led_state_publisher.LEDStatePublisher.led_info_publisher
Definition at line 41 of file led_state_publisher.py.
Referenced by autonomy_state_machine.led_state_publisher.LEDStatePublisher.signal_waypoint_success().
node
autonomy_state_machine.led_state_publisher.LEDStatePublisher.node
Definition at line 38 of file led_state_publisher.py.
Referenced by autonomy_state_machine.mission_aruco_detector.MissionArUcoDetector.create_arm_alignment_command(), autonomy_state_machine.mission_aruco_detector.MissionArUcoDetector.detect_mission_tags(), autonomy_autonomous_typing.aruco_detection.typing_aruco_detector.TypingArUcoDetector.detect_typing_tags(), and autonomy_state_machine.frontend_interface.FrontendInterface.register_state_callback().
The documentation for this class was generated from the following file:
code/state_management/autonomy_state_machine/led_state_publisher.py