URC Machiato 2026 Autonomy: autonomy_navigation.motion_controller.MotionController Class Reference
autonomy_navigation.motion_controller.MotionController Class Reference
Public Member Functions
def __init__ (self)
def initialize (self)
def set_velocity (self, float linear_x, float angular_z)
def execute_velocity_command (self)
def stop_motors (self)
Tuple[float, float] calculate_wheel_velocities (self, float linear_x, float angular_z)
def update_odometry (self, float left_wheel_velocity, float right_wheel_velocity, float dt)
Twist get_current_velocity (self)
Twist get_target_velocity (self)
bool is_at_target_velocity (self, float tolerance=0.1)
def set_emergency_stop (self, bool active)
dict get_motor_status (self)
def calibrate_motors (self)
def reset_controller (self)
def shutdown (self)
Public Attributes
max_linear_speed
max_angular_speed
acceleration_limit
deceleration_limit
wheel_separation
wheel_radius
current_velocity
target_velocity
emergency_stop_active
Detailed Description
Low-level motion control for autonomous navigation.
Provides:
- Velocity command execution
- Trajectory following
- Emergency stop handling
- Odometry feedback
Definition at line 23 of file motion_controller.py.
Constructor & Destructor Documentation
__init__()
def autonomy_navigation.motion_controller.MotionController.__init__ (self)
Definition at line 34 of file motion_controller.py.
Member Function Documentation
calculate_wheel_velocities()
Tuple[float, float] autonomy_navigation.motion_controller.MotionController.calculate_wheel_velocities (self, float linear_x, float angular_z)
Calculate individual wheel velocities for differential drive
Definition at line 97 of file motion_controller.py.
References autonomy_navigation.motion_controller.MotionController.wheel_separation.
calibrate_motors()
def autonomy_navigation.motion_controller.MotionController.calibrate_motors (self)
Calibrate motor controllers
Definition at line 148 of file motion_controller.py.
execute_velocity_command()
def autonomy_navigation.motion_controller.MotionController.execute_velocity_command (self)
Execute current velocity command
Definition at line 73 of file motion_controller.py.
References autonomy_navigation.motion_controller.MotionController.current_velocity, autonomy_navigation.motion_controller.MotionController.emergency_stop_active, autonomy_navigation.motion_controller.MotionController.stop_motors(), and autonomy_navigation.motion_controller.MotionController.target_velocity.
get_current_velocity()
Twist autonomy_navigation.motion_controller.MotionController.get_current_velocity (self)
Get current velocity
Definition at line 114 of file motion_controller.py.
References autonomy_navigation.motion_controller.MotionController.current_velocity.
get_motor_status()
dict autonomy_navigation.motion_controller.MotionController.get_motor_status (self)
Get motor status information
Definition at line 135 of file motion_controller.py.
get_target_velocity()
Twist autonomy_navigation.motion_controller.MotionController.get_target_velocity (self)
Get target velocity
Definition at line 118 of file motion_controller.py.
References autonomy_navigation.motion_controller.MotionController.target_velocity.
initialize()
def autonomy_navigation.motion_controller.MotionController.initialize (self)
Initialize motion controller
Definition at line 54 of file motion_controller.py.
is_at_target_velocity()
bool autonomy_navigation.motion_controller.MotionController.is_at_target_velocity (self, float tolerance = 0.1)
Check if current velocity matches target
Definition at line 122 of file motion_controller.py.
References autonomy_navigation.motion_controller.MotionController.current_velocity, and autonomy_navigation.motion_controller.MotionController.target_velocity.
reset_controller()
def autonomy_navigation.motion_controller.MotionController.reset_controller (self)
Reset controller state
Definition at line 157 of file motion_controller.py.
set_emergency_stop()
def autonomy_navigation.motion_controller.MotionController.set_emergency_stop (self, bool active)
Set emergency stop state
Definition at line 129 of file motion_controller.py.
References autonomy_navigation.motion_controller.MotionController.emergency_stop_active, and autonomy_navigation.motion_controller.MotionController.stop_motors().
set_velocity()
def autonomy_navigation.motion_controller.MotionController.set_velocity (self, float linear_x, float angular_z)
Set target velocity
Definition at line 62 of file motion_controller.py.
shutdown()
def autonomy_navigation.motion_controller.MotionController.shutdown (self)
Shutdown motion controller
Definition at line 166 of file motion_controller.py.
References autonomy_navigation.motion_controller.MotionController.stop_motors().
stop_motors()
def autonomy_navigation.motion_controller.MotionController.stop_motors (self)
Emergency stop all motors
Definition at line 87 of file motion_controller.py.
References autonomy_navigation.motion_controller.MotionController.current_velocity, and autonomy_navigation.motion_controller.MotionController.target_velocity.
Referenced by autonomy_navigation.motion_controller.MotionController.execute_velocity_command(), autonomy_navigation.motion_controller.MotionController.set_emergency_stop(), and autonomy_navigation.motion_controller.MotionController.shutdown().
update_odometry()
def autonomy_navigation.motion_controller.MotionController.update_odometry (self, float left_wheel_velocity, float right_wheel_velocity, float dt)
Update odometry from wheel encoders
Definition at line 105 of file motion_controller.py.
Member Data Documentation
acceleration_limit
autonomy_navigation.motion_controller.MotionController.acceleration_limit
Definition at line 37 of file motion_controller.py.
current_velocity
autonomy_navigation.motion_controller.MotionController.current_velocity
Definition at line 45 of file motion_controller.py.
Referenced by autonomy_navigation.motion_controller.MotionController.execute_velocity_command(), autonomy_navigation.motion_controller.MotionController.get_current_velocity(), autonomy_navigation.motion_controller.MotionController.is_at_target_velocity(), and autonomy_navigation.motion_controller.MotionController.stop_motors().
deceleration_limit
autonomy_navigation.motion_controller.MotionController.deceleration_limit
Definition at line 38 of file motion_controller.py.
emergency_stop_active
autonomy_navigation.motion_controller.MotionController.emergency_stop_active
Definition at line 47 of file motion_controller.py.
Referenced by autonomy_navigation.motion_controller.MotionController.execute_velocity_command(), and autonomy_navigation.motion_controller.MotionController.set_emergency_stop().
max_angular_speed
autonomy_navigation.motion_controller.MotionController.max_angular_speed
Definition at line 36 of file motion_controller.py.
max_linear_speed
autonomy_navigation.motion_controller.MotionController.max_linear_speed
Definition at line 35 of file motion_controller.py.
target_velocity
autonomy_navigation.motion_controller.MotionController.target_velocity
Definition at line 46 of file motion_controller.py.
Referenced by autonomy_navigation.motion_controller.MotionController.execute_velocity_command(), autonomy_navigation.motion_controller.MotionController.get_target_velocity(), autonomy_navigation.motion_controller.MotionController.is_at_target_velocity(), and autonomy_navigation.motion_controller.MotionController.stop_motors().
wheel_radius
autonomy_navigation.motion_controller.MotionController.wheel_radius
Definition at line 42 of file motion_controller.py.
wheel_separation
autonomy_navigation.motion_controller.MotionController.wheel_separation
Definition at line 41 of file motion_controller.py.
Referenced by autonomy_navigation.motion_controller.MotionController.calculate_wheel_velocities().
The documentation for this class was generated from the following file:
code/navigation/autonomy_navigation/motion_controller.py