URC Machiato 2026 Autonomy: autonomy_navigation.terrain_classifier.TerrainClassifier Class Reference
autonomy_navigation.terrain_classifier.TerrainClassifier Class Reference
Public Member Functions
def __init__ (self)
def initialize (self)
TerrainType classify_terrain (self, dict sensor_data)
TerrainProperties get_terrain_properties (self, TerrainType terrain_type)
float assess_traversability (self, Tuple[float, float] position, float lookahead_distance=2.0)
float recommend_speed (self, TerrainType terrain_type, float current_speed)
float calculate_terrain_cost (self, TerrainType terrain_type, float distance)
List[dict] detect_hazards (self, dict sensor_data)
def update_terrain_map (self, Tuple[float, float] position, TerrainType terrain_type)
def reset_classifier (self)
def shutdown (self)
Public Attributes
classification_window
update_rate
terrain_properties
Detailed Description
Terrain classification and analysis system.
Analyzes sensor data to classify terrain and provide
navigation guidance for adaptive behavior.
Definition at line 40 of file terrain_classifier.py.
Constructor & Destructor Documentation
__init__()
def autonomy_navigation.terrain_classifier.TerrainClassifier.__init__ (self)
Definition at line 48 of file terrain_classifier.py.
Member Function Documentation
assess_traversability()
float autonomy_navigation.terrain_classifier.TerrainClassifier.assess_traversability (self, Tuple[float, float] position, float lookahead_distance = 2.0)
Assess terrain traversability ahead
Definition at line 113 of file terrain_classifier.py.
calculate_terrain_cost()
float autonomy_navigation.terrain_classifier.TerrainClassifier.calculate_terrain_cost (self, TerrainType terrain_type, float distance)
Calculate path cost for terrain segment
Definition at line 135 of file terrain_classifier.py.
References autonomy_navigation.terrain_classifier.TerrainClassifier.get_terrain_properties().
classify_terrain()
TerrainType autonomy_navigation.terrain_classifier.TerrainClassifier.classify_terrain (self, dict sensor_data)
Classify terrain type from sensor data
Definition at line 101 of file terrain_classifier.py.
detect_hazards()
List[dict] autonomy_navigation.terrain_classifier.TerrainClassifier.detect_hazards (self, dict sensor_data)
Detect terrain hazards
Definition at line 149 of file terrain_classifier.py.
get_terrain_properties()
TerrainProperties autonomy_navigation.terrain_classifier.TerrainClassifier.get_terrain_properties (self, TerrainType terrain_type)
Get properties for terrain type
Definition at line 109 of file terrain_classifier.py.
References autonomy_navigation.terrain_classifier.TerrainClassifier.terrain_properties.
Referenced by autonomy_navigation.terrain_classifier.TerrainClassifier.calculate_terrain_cost(), and autonomy_navigation.terrain_classifier.TerrainClassifier.recommend_speed().
initialize()
def autonomy_navigation.terrain_classifier.TerrainClassifier.initialize (self)
Initialize terrain classifier
Definition at line 94 of file terrain_classifier.py.
recommend_speed()
float autonomy_navigation.terrain_classifier.TerrainClassifier.recommend_speed (self, TerrainType terrain_type, float current_speed)
Recommend appropriate speed for terrain
Definition at line 122 of file terrain_classifier.py.
References autonomy_navigation.terrain_classifier.TerrainClassifier.get_terrain_properties().
reset_classifier()
def autonomy_navigation.terrain_classifier.TerrainClassifier.reset_classifier (self)
Reset classifier state
Definition at line 166 of file terrain_classifier.py.
shutdown()
def autonomy_navigation.terrain_classifier.TerrainClassifier.shutdown (self)
Shutdown terrain classifier
Definition at line 173 of file terrain_classifier.py.
update_terrain_map()
def autonomy_navigation.terrain_classifier.TerrainClassifier.update_terrain_map (self, Tuple[float, float] position, TerrainType terrain_type)
Update internal terrain map
Definition at line 157 of file terrain_classifier.py.
Member Data Documentation
classification_window
autonomy_navigation.terrain_classifier.TerrainClassifier.classification_window
Definition at line 50 of file terrain_classifier.py.
terrain_properties
autonomy_navigation.terrain_classifier.TerrainClassifier.terrain_properties
Definition at line 54 of file terrain_classifier.py.
Referenced by autonomy_navigation.terrain_classifier.TerrainClassifier.get_terrain_properties().
update_rate
autonomy_navigation.terrain_classifier.TerrainClassifier.update_rate
Definition at line 51 of file terrain_classifier.py.
The documentation for this class was generated from the following file:
code/navigation/autonomy_navigation/terrain_classifier.py