URC Machiato 2026 Autonomy: tests.test_state_machine.TestStates Class Reference
tests.test_state_machine.TestStates Class Reference
Public Member Functions
def test_system_states_exist (self)
def test_autonomous_substates_exist (self)
def test_state_metadata_exists (self)
def test_boot_to_idle_transition_valid (self)
def test_idle_to_boot_transition_invalid (self)
def test_any_state_to_safety_valid (self)
def test_required_subsystems_autonomous (self)
def test_required_subsystems_autonomous_navigation (self)
Detailed Description
Test state definitions and metadata.
Definition at line 24 of file test_state_machine.py.
Member Function Documentation
test_any_state_to_safety_valid()
def tests.test_state_machine.TestStates.test_any_state_to_safety_valid (self)
Test that any state can transition to SAFETY.
Definition at line 74 of file test_state_machine.py.
References autonomy_state_machine.states.get_state_metadata().
test_autonomous_substates_exist()
def tests.test_state_machine.TestStates.test_autonomous_substates_exist (self)
Test that autonomous substates are defined.
Definition at line 44 of file test_state_machine.py.
test_boot_to_idle_transition_valid()
def tests.test_state_machine.TestStates.test_boot_to_idle_transition_valid (self)
Test that BOOT -> IDLE transition is valid.
Definition at line 66 of file test_state_machine.py.
References autonomy_state_machine.states.is_valid_transition().
test_idle_to_boot_transition_invalid()
def tests.test_state_machine.TestStates.test_idle_to_boot_transition_invalid (self)
Test that IDLE -> BOOT transition is invalid.
Definition at line 70 of file test_state_machine.py.
References autonomy_state_machine.states.is_valid_transition().
test_required_subsystems_autonomous()
def tests.test_state_machine.TestStates.test_required_subsystems_autonomous (self)
Test required subsystems for autonomous state.
Definition at line 84 of file test_state_machine.py.
References autonomy_state_machine.states.get_required_subsystems().
test_required_subsystems_autonomous_navigation()
def tests.test_state_machine.TestStates.test_required_subsystems_autonomous_navigation (self)
Test required subsystems for autonomous navigation mission.
Definition at line 91 of file test_state_machine.py.
References autonomy_state_machine.states.get_required_subsystems().
test_state_metadata_exists()
def tests.test_state_machine.TestStates.test_state_metadata_exists (self)
Test that metadata exists for all states.
Definition at line 59 of file test_state_machine.py.
References autonomy_state_machine.states.get_state_metadata().
test_system_states_exist()
def tests.test_state_machine.TestStates.test_system_states_exist (self)
Test that all system states are defined.
Definition at line 27 of file test_state_machine.py.
The documentation for this class was generated from the following file:
code/state_management/tests/test_state_machine.py